package com.eim.winder.div;

import com.eim.winder.db.AlertSettings;
import com.eim.winder.db.Location;

import java.util.ArrayList;

/**
 * Created by Mari on 31.01.2016.
 */
public class Locations {
    public static final String[] locations = {"Trondheim Sentrum", "Lade", "Ila", "Orkanger", "Stjørdal","Hatmountainvalley", "Åre", "UtiGokk"};

    public static ArrayList<AlertSettings> getTestAlertList() {
            ArrayList<AlertSettings> testAlerts = new ArrayList<>();
            Location loc = new Location();
            loc.setName("Trondheim");
            loc.setId(-1);
            loc.setXmlURL("http://www.yr.no/place/Norway/Sør-Trøndelag/Trondheim/Trondheim/forecast.xml");
            Location loc2 = new Location();
            loc2.setName("Ørlandet");
            loc2.setId(-2);
            loc2.setXmlURL("http://www.yr.no/place/Norway/Sør-Trøndelag/Ørland/Ørland_lufthavn/forecast.xml");
            Location loc3 = new Location();
            loc3.setName("Stjørdal");
            loc3.setId(-3);
            loc3.setXmlURL("http://www.yr.no/place/Norway/Nord-Trøndelag/Stjørdal/Stjørdal/forecast.xml");

            testAlerts.add(new AlertSettings(1, -10, -20, 9.0, 20.0, 6.0, 12.0, "SW", 1, 2, 1, 1, 1, 1, 1, 1, 1, "ic_sun", loc));
            testAlerts.add(new AlertSettings(1, -10, -20, 9.0, 20.0, 6.0, 12.0, "SW", 1, 2, 6, 1, 1, 1, 1, 1, 1, "ic_sun", loc2));
            testAlerts.add(new AlertSettings(1, -10, -20, 9.0, 20.0, 6.0, 12.0, "SW", 1, 0.5, 1, 1, 1, 1, 1, 1, 1, "ic_sun", loc3));
            return testAlerts;
    }
    public static final String[][] locationsComplete = new String[][]{
            {"Asak kirke", "http://www.yr.no/sted/Norge/Østfold/Halden/Asak_kirke/varsel.xml"},
            {"Berg kirke", "http://www.yr.no/sted/Norge/Østfold/Halden/Berg_kirke/varsel.xml"},
            {"Brekke", "http://www.yr.no/sted/Norge/Østfold/Halden/Brekke~35224/varsel.xml"},
            {"Brødløs", "http://www.yr.no/sted/Norge/Østfold/Halden/Brødløs/varsel.xml"},
            {"Demma", "http://www.yr.no/sted/Norge/Østfold/Halden/Demma/varsel.xml"},
            {"Ertehytta", "http://www.yr.no/sted/Norge/Østfold/Halden/Ertehytta/varsel.xml"},
            {"Grøvet", "http://www.yr.no/sted/Norge/Østfold/Halden/Grøvet/varsel.xml"},
            {"Halden", "http://www.yr.no/sted/Norge/Østfold/Halden/Halden/varsel.xml"},
            {"Halden postkontor", "http://www.yr.no/sted/Norge/Østfold/Halden/Halden_postkontor/varsel.xml"},
            {"Haugtjernhytta", "http://www.yr.no/sted/Norge/Østfold/Halden/Haugtjernhytta/varsel.xml"},
            {"Holtet", "http://www.yr.no/sted/Norge/Østfold/Halden/Holtet/varsel.xml"},
            {"Idd", "http://www.yr.no/sted/Norge/Østfold/Halden/Idd/varsel.xml"},
            {"Idd kirke", "http://www.yr.no/sted/Norge/Østfold/Halden/Idd_kirke/varsel.xml"},
            {"Immanuels kirke", "http://www.yr.no/sted/Norge/Østfold/Halden/Immanuels_kirke/varsel.xml"},
            {"Isebakke", "http://www.yr.no/sted/Norge/Østfold/Halden/Isebakke/varsel.xml"},
            {"Kitterød", "http://www.yr.no/sted/Norge/Østfold/Halden/Kitterød/varsel.xml"},
            {"Knardal", "http://www.yr.no/sted/Norge/Østfold/Halden/Knardal/varsel.xml"},
            {"Kornsjø", "http://www.yr.no/sted/Norge/Østfold/Halden/Kornsjø/varsel.xml"},
            {"Lerdalen", "http://www.yr.no/sted/Norge/Østfold/Halden/Lerdalen/varsel.xml"},
            {"Prestebakke", "http://www.yr.no/sted/Norge/Østfold/Halden/Prestebakke~23368/varsel.xml"},
            {"Prestebakke kirke", "http://www.yr.no/sted/Norge/Østfold/Halden/Prestebakke_kirke/varsel.xml"},
            {"Rokke kirke", "http://www.yr.no/sted/Norge/Østfold/Halden/Rokke_kirke/varsel.xml"},
            {"Skogskroken", "http://www.yr.no/sted/Norge/Østfold/Halden/Skogskroken/varsel.xml"},
            {"Sponvika", "http://www.yr.no/sted/Norge/Østfold/Halden/Sponvika/varsel.xml"},
            {"Søndre Enningdalen kirke", "http://www.yr.no/sted/Norge/Østfold/Halden/Søndre_Enningdalen_kirke/varsel.xml"},
            {"Tistedal", "http://www.yr.no/sted/Norge/Østfold/Halden/Tistedal/varsel.xml"},
            {"Tistedal kirke", "http://www.yr.no/sted/Norge/Østfold/Halden/Tistedal_kirke/varsel.xml"},
            {"Årbakke", "http://www.yr.no/sted/Norge/Østfold/Halden/Årbakke/varsel.xml"},
            {"Bellevue", "http://www.yr.no/sted/Norge/Østfold/Moss/Bellevue/varsel.xml"},
            {"Bevøya", "http://www.yr.no/sted/Norge/Østfold/Moss/Bevøya/varsel.xml"},
            {"Dillingøya", "http://www.yr.no/sted/Norge/Østfold/Moss/Dillingøya/varsel.xml"},
            {"Fiske", "http://www.yr.no/sted/Norge/Østfold/Moss/Fiske/varsel.xml"},
            {"Framnes", "http://www.yr.no/sted/Norge/Østfold/Moss/Framnes/varsel.xml"},
            {"Gjerrebogen", "http://www.yr.no/sted/Norge/Østfold/Moss/Gjerrebogen/varsel.xml"},
            {"Grindvoll", "http://www.yr.no/sted/Norge/Østfold/Moss/Grindvoll/varsel.xml"},
            {"Gullholmen", "http://www.yr.no/sted/Norge/Østfold/Moss/Gullholmen/varsel.xml"},
            {"Hopperen", "http://www.yr.no/sted/Norge/Østfold/Moss/Hopperen/varsel.xml"},
            {"Jeløy kirke", "http://www.yr.no/sted/Norge/Østfold/Moss/Jeløy_kirke/varsel.xml"},
            {"Kambo", "http://www.yr.no/sted/Norge/Østfold/Moss/Kambo/varsel.xml"},
            {"Klommesten", "http://www.yr.no/sted/Norge/Østfold/Moss/Klommesten/varsel.xml"},
            {"Krapfoss", "http://www.yr.no/sted/Norge/Østfold/Moss/Krapfoss/varsel.xml"},
            {"Krossern", "http://www.yr.no/sted/Norge/Østfold/Moss/Krossern/varsel.xml"},
            {"Malakoff", "http://www.yr.no/sted/Norge/Østfold/Moss/Malakoff/varsel.xml"},
            {"Melløs", "http://www.yr.no/sted/Norge/Østfold/Moss/Melløs/varsel.xml"},
            {"Moss", "http://www.yr.no/sted/Norge/Østfold/Moss/Moss/varsel.xml"},
            {"Moss kirke", "http://www.yr.no/sted/Norge/Østfold/Moss/Moss_kirke/varsel.xml"},
            {"Refsnes", "http://www.yr.no/sted/Norge/Østfold/Moss/Refsnes/varsel.xml"},
            {"Skarmyra", "http://www.yr.no/sted/Norge/Østfold/Moss/Skarmyra/varsel.xml"},
            {"Skihytta", "http://www.yr.no/sted/Norge/Østfold/Moss/Skihytta/varsel.xml"},
            {"Øre", "http://www.yr.no/sted/Norge/Østfold/Moss/Øre/varsel.xml"},
            {"Ørehavna", "http://www.yr.no/sted/Norge/Østfold/Moss/Ørehavna/varsel.xml"},
            {"Alvim", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Alvim~2229863/varsel.xml"},
            {"Alvimhaugen", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Alvimhaugen/varsel.xml"},
            {"Borgen", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Borgen/varsel.xml"},
            {"Borgenhaugen", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Borgenhaugen~2230027/varsel.xml"},
            {"Borgenhaugen", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Borgenhaugen/varsel.xml"},
            {"Enenda", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Enenda/varsel.xml"},
            {"Fritznerbakken", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Fritznerbakken/varsel.xml"},
            {"Gleng", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Gleng/varsel.xml"},
            {"Greåker", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Greåker/varsel.xml"},
            {"Greåker kirke", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Greåker_kirke/varsel.xml"},
            {"Grålum", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Grålum/varsel.xml"},
            {"Hafslund", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Hafslund~48540/varsel.xml"},
            {"Hafslund kirke", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Hafslund_kirke/varsel.xml"},
            {"Hanestad", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Hanestad/varsel.xml"},
            {"Hannestad", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Hannestad/varsel.xml"},
            {"Harehjellhytta", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Harehjellhytta/varsel.xml"},
            {"Hasle", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Hasle/varsel.xml"},
            {"Holleby kirke", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Holleby_kirke/varsel.xml"},
            {"Høysand", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Høysand/varsel.xml"},
            {"Ingedal kirke", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Ingedal_kirke/varsel.xml"},
            {"Ise", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Ise~507783/varsel.xml"},
            {"Klokkerød", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Klokkerød/varsel.xml"},
            {"Kvastebyen", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Kvastebyen/varsel.xml"},
            {"Navestad", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Navestad/varsel.xml"},
            {"Navestad", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Navestad/varsel.xml"},
            {"Nordberg", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Nordberg/varsel.xml"},
            {"Nordre Bjørnstad", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Nordre_Bjørnstad/varsel.xml"},
            {"Opsund", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Opsund/varsel.xml"},
            {"Rødsøya", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Rødsøya/varsel.xml"},
            {"Sandbakken", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Sandbakken~48621/varsel.xml"},
            {"Sandesund", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Sandesund/varsel.xml"},
            {"Sarpsborg", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Sarpsborg/varsel.xml"},
            {"Sarpsborg kirke", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Sarpsborg_kirke/varsel.xml"},
            {"Skjeberg", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Skjeberg/varsel.xml"},
            {"Skjeberg kirke", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Skjeberg_kirke/varsel.xml"},
            {"Skjebergdalen kirke", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Skjebergdalen_kirke/varsel.xml"},
            {"Solli kirke", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Solli_kirke/varsel.xml"},
            {"Storhaug", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Storhaug/varsel.xml"},
            {"Tune kirke", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Tune_kirke/varsel.xml"},
            {"Ullerøy kirke", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Ullerøy_kirke/varsel.xml"},
            {"Valaskjold", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Valaskjold/varsel.xml"},
            {"Varteig kirke", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Varteig_kirke/varsel.xml"},
            {"Vesteng", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Vesteng/varsel.xml"},
            {"Yven", "http://www.yr.no/sted/Norge/Østfold/Sarpsborg/Yven/varsel.xml"},
            {"Ambjørnrød", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Ambjørnrød/varsel.xml"},
            {"Apenesfjellet", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Apenesfjellet/varsel.xml"},
            {"Barkedalen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Barkedalen/varsel.xml"},
            {"Begby", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Begby/varsel.xml"},
            {"Borge kirke", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Borge_kirke/varsel.xml"},
            {"Bydalen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Bydalen/varsel.xml"},
            {"Cicignon", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Cicignon/varsel.xml"},
            {"Damyr", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Damyr/varsel.xml"},
            {"Engelsviken", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Engelsviken/varsel.xml"},
            {"Falchåsen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Falchåsen/varsel.xml"},
            {"Fredrikstad", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Fredrikstad/varsel.xml"},
            {"Fredrikstad Domkirke", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Fredrikstad_Domkirke/varsel.xml"},
            {"Frydenberg", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Frydenberg/varsel.xml"},
            {"Gamle Glemmen kirke", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Gamle_Glemmen_kirke/varsel.xml"},
            {"Gamlebyen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Gamlebyen/varsel.xml"},
            {"Glemmen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Glemmen/varsel.xml"},
            {"Glemmen nye kirke", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Glemmen_nye_kirke/varsel.xml"},
            {"Glombo", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Glombo/varsel.xml"},
            {"Gluppe", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Gluppe/varsel.xml"},
            {"Gressvik", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Gressvik/varsel.xml"},
            {"Gressvik kirke", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Gressvik_kirke/varsel.xml"},
            {"Gullmoen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Gullmoen/varsel.xml"},
            {"Hasseldalen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Hasseldalen/varsel.xml"},
            {"Hassingen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Hassingen/varsel.xml"},
            {"Hauge", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Hauge/varsel.xml"},
            {"Holm", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Holm/varsel.xml"},
            {"Holmen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Holmen/varsel.xml"},
            {"Husløs", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Husløs/varsel.xml"},
            {"Kapelfjellet", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Kapelfjellet/varsel.xml"},
            {"Kjerre", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Kjerre/varsel.xml"},
            {"Kjølstad kirke", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Kjølstad_kirke~2328384/varsel.xml"},
            {"Kjølstad kirke", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Kjølstad_kirke~2826288/varsel.xml"},
            {"Kjølstadløkka", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Kjølstadløkka/varsel.xml"},
            {"Kongsten", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Kongsten/varsel.xml"},
            {"Krossnes", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Krossnes/varsel.xml"},
            {"Kråkerøy kirke", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Kråkerøy_kirke/varsel.xml"},
            {"Kuhaugen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Kuhaugen/varsel.xml"},
            {"Lahellemoen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Lahellemoen/varsel.xml"},
            {"Leie", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Leie/varsel.xml"},
            {"Lervik", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Lervik/varsel.xml"},
            {"Lisleby", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Lisleby/varsel.xml"},
            {"Lunde", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Lunde/varsel.xml"},
            {"Lundeskogen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Lundeskogen/varsel.xml"},
            {"Lundheim", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Lundheim/varsel.xml"},
            {"Manstad", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Manstad/varsel.xml"},
            {"Nabbetorp", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Nabbetorp/varsel.xml"},
            {"Nylende", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Nylende/varsel.xml"},
            {"Nøkleby", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Nøkleby/varsel.xml"},
            {"Onsøy kirke", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Onsøy_kirke/varsel.xml"},
            {"Pettersand", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Pettersand/varsel.xml"},
            {"Putten", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Putten/varsel.xml"},
            {"Riverside", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Riverside/varsel.xml"},
            {"Rolvsøy kirke", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Rolvsøy_kirke/varsel.xml"},
            {"Roppestad", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Roppestad/varsel.xml"},
            {"Rostadneset", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Rostadneset/varsel.xml"},
            {"Rød", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Rød~33668/varsel.xml"},
            {"Sellebakk", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Sellebakk/varsel.xml"},
            {"Skihytta", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Skihytta/varsel.xml"},
            {"Skjærvika", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Skjærvika/varsel.xml"},
            {"Skjærvika", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Skjærvika/varsel.xml"},
            {"Skåra", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Skåra/varsel.xml"},
            {"Slevik", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Slevik~508530/varsel.xml"},
            {"Smertu", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Smertu/varsel.xml"},
            {"Snekkerhaugen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Snekkerhaugen/varsel.xml"},
            {"Struten", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Struten/varsel.xml"},
            {"Strømtangen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Strømtangen/varsel.xml"},
            {"Sundløkka", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Sundløkka/varsel.xml"},
            {"Toremyr", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Toremyr/varsel.xml"},
            {"Torp", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Torp/varsel.xml"},
            {"Torsnes kirke", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Torsnes_kirke/varsel.xml"},
            {"Trara", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Trara/varsel.xml"},
            {"Trolldalen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Trolldalen/varsel.xml"},
            {"Valle", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Valle/varsel.xml"},
            {"Vaterland", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Vaterland/varsel.xml"},
            {"Veel", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Veel/varsel.xml"},
            {"Vestre Vikene", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Vestre_Vikene/varsel.xml"},
            {"Veum", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Veum/varsel.xml"},
            {"Vikene", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Vikene/varsel.xml"},
            {"Viker", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Viker/varsel.xml"},
            {"Ødegården", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Ødegården/varsel.xml"},
            {"Ørebekk", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Ørebekk/varsel.xml"},
            {"Ørmen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Ørmen/varsel.xml"},
            {"Østre Fredrikstad kirke", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Østre_Fredrikstad_kirke/varsel.xml"},
            {"Østre Vikene", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Østre_Vikene/varsel.xml"},
            {"Øyenkilen", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Øyenkilen/varsel.xml"},
            {"Ålestranda", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Ålestranda/varsel.xml"},
            {"Årum", "http://www.yr.no/sted/Norge/Østfold/Fredrikstad/Årum~48615/varsel.xml"},
            {"Dypedal", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Dypedal/varsel.xml"},
            {"Hauge", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Hauge/varsel.xml"},
            {"Herføl", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Herføl~23320/varsel.xml"},
            {"Hvaler kirke", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Hvaler_kirke/varsel.xml"},
            {"Nedgården", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Nedgården/varsel.xml"},
            {"Papper", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Papper/varsel.xml"},
            {"Rød", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Rød/varsel.xml"},
            {"Sand", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Sand/varsel.xml"},
            {"Skipstadsand", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Skipstadsand/varsel.xml"},
            {"Skjelsbu", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Skjelsbu/varsel.xml"},
            {"Skjærhalden", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Skjærhalden/varsel.xml"},
            {"Spjærøy kirke", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Spjærøy_kirke/varsel.xml"},
            {"Torbjørnskjær", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Torbjørnskjær/varsel.xml"},
            {"Utgård", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Utgård/varsel.xml"},
            {"Vesterøy", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Vesterøy/varsel.xml"},
            {"Viker", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Viker/varsel.xml"},
            {"Øvre Utgård", "http://www.yr.no/sted/Norge/Østfold/Hvaler/Øvre_Utgård/varsel.xml"},
            {"Aremark", "http://www.yr.no/sted/Norge/Østfold/Aremark/Aremark~2379071/varsel.xml"},
            {"Aremark kirke", "http://www.yr.no/sted/Norge/Østfold/Aremark/Aremark_kirke/varsel.xml"},
            {"Aspern", "http://www.yr.no/sted/Norge/Østfold/Aremark/Aspern/varsel.xml"},
            {"Bjørkebekk", "http://www.yr.no/sted/Norge/Østfold/Aremark/Bjørkebekk/varsel.xml"},
            {"Budalsvika", "http://www.yr.no/sted/Norge/Østfold/Aremark/Budalsvika/varsel.xml"},
            {"Fossby", "http://www.yr.no/sted/Norge/Østfold/Aremark/Fossby/varsel.xml"},
            {"Holmgill kirke", "http://www.yr.no/sted/Norge/Østfold/Aremark/Holmgill_kirke/varsel.xml"},
            {"Store Le", "http://www.yr.no/sted/Norge/Østfold/Aremark/Store_Le/varsel.xml"},
            {"Strømsfoss", "http://www.yr.no/sted/Norge/Østfold/Aremark/Strømsfoss/varsel.xml"},
            {"Trollhøgda", "http://www.yr.no/sted/Norge/Østfold/Aremark/Trollhøgda/varsel.xml"},
            {"Børresrud", "http://www.yr.no/sted/Norge/Østfold/Marker/Børresrud/varsel.xml"},
            {"Klund kirke", "http://www.yr.no/sted/Norge/Østfold/Marker/Klund_kirke/varsel.xml"},
            {"Kroksund", "http://www.yr.no/sted/Norge/Østfold/Marker/Kroksund/varsel.xml"},
            {"Otteid vestre", "http://www.yr.no/sted/Norge/Østfold/Marker/Otteid_vestre/varsel.xml"},
            {"Rødenes kirke", "http://www.yr.no/sted/Norge/Østfold/Marker/Rødenes_kirke/varsel.xml"},
            {"Ørje", "http://www.yr.no/sted/Norge/Østfold/Marker/Ørje/varsel.xml"},
            {"Ørje kirke", "http://www.yr.no/sted/Norge/Østfold/Marker/Ørje_kirke/varsel.xml"},
            {"Øymark kirke", "http://www.yr.no/sted/Norge/Østfold/Marker/Øymark_kirke/varsel.xml"},
            {"Haukenestårnet", "http://www.yr.no/sted/Norge/Østfold/Rømskog/Haukenestårnet/varsel.xml"},
            {"Rømskog", "http://www.yr.no/sted/Norge/Østfold/Rømskog/Rømskog/varsel.xml"},
            {"Rømskog kirke", "http://www.yr.no/sted/Norge/Østfold/Rømskog/Rømskog_kirke/varsel.xml"},
            {"Røvasshøgda", "http://www.yr.no/sted/Norge/Østfold/Rømskog/Røvasshøgda/varsel.xml"},
            {"Slavasshøgda", "http://www.yr.no/sted/Norge/Østfold/Rømskog/Slavasshøgda/varsel.xml"},
            {"Trandum", "http://www.yr.no/sted/Norge/Østfold/Rømskog/Trandum/varsel.xml"},
            {"Trandumseter", "http://www.yr.no/sted/Norge/Østfold/Rømskog/Trandumseter/varsel.xml"},
            {"Trosterud", "http://www.yr.no/sted/Norge/Østfold/Rømskog/Trosterud/varsel.xml"},
            {"Tørnby", "http://www.yr.no/sted/Norge/Østfold/Rømskog/Tørnby/varsel.xml"},
            {"Bechs kapell", "http://www.yr.no/sted/Norge/Østfold/Trøgstad/Bechs_kapell/varsel.xml"},
            {"Båstad kirke", "http://www.yr.no/sted/Norge/Østfold/Trøgstad/Båstad_kirke/varsel.xml"},
            {"Havnås", "http://www.yr.no/sted/Norge/Østfold/Trøgstad/Havnås~61843/varsel.xml"},
            {"Heiås", "http://www.yr.no/sted/Norge/Østfold/Trøgstad/Heiås/varsel.xml"},
            {"Mørkfoss", "http://www.yr.no/sted/Norge/Østfold/Trøgstad/Mørkfoss/varsel.xml"},
            {"Skjønhaug", "http://www.yr.no/sted/Norge/Østfold/Trøgstad/Skjønhaug/varsel.xml"},
            {"Tosebygda", "http://www.yr.no/sted/Norge/Østfold/Trøgstad/Tosebygda/varsel.xml"},
            {"Trøgstad", "http://www.yr.no/sted/Norge/Østfold/Trøgstad/Trøgstad/varsel.xml"},
            {"Trøgstad kirke", "http://www.yr.no/sted/Norge/Østfold/Trøgstad/Trøgstad_kirke/varsel.xml"},
            {"Heli kirke", "http://www.yr.no/sted/Norge/Østfold/Spydeberg/Heli_kirke/varsel.xml"},
            {"Hovin kirke", "http://www.yr.no/sted/Norge/Østfold/Spydeberg/Hovin_kirke/varsel.xml"},
            {"Mørk søndre", "http://www.yr.no/sted/Norge/Østfold/Spydeberg/Mørk_søndre/varsel.xml"},
            {"Spydeberg", "http://www.yr.no/sted/Norge/Østfold/Spydeberg/Spydeberg/varsel.xml"},
            {"Spydeberg", "http://www.yr.no/sted/Norge/Østfold/Spydeberg/Spydeberg~60857/varsel.xml"},
            {"Spydeberg kirke", "http://www.yr.no/sted/Norge/Østfold/Spydeberg/Spydeberg_kirke/varsel.xml"},
            {"Tomter", "http://www.yr.no/sted/Norge/Østfold/Spydeberg/Tomter/varsel.xml"},
            {"Askim", "http://www.yr.no/sted/Norge/Østfold/Askim/Askim/varsel.xml"},
            {"Askim", "http://www.yr.no/sted/Norge/Østfold/Askim/Askim~2764239/varsel.xml"},
            {"Askim kirke", "http://www.yr.no/sted/Norge/Østfold/Askim/Askim_kirke/varsel.xml"},
            {"Gurud", "http://www.yr.no/sted/Norge/Østfold/Askim/Gurud~2232828/varsel.xml"},
            {"Kykkelsrud", "http://www.yr.no/sted/Norge/Østfold/Askim/Kykkelsrud/varsel.xml"},
            {"Langnes", "http://www.yr.no/sted/Norge/Østfold/Askim/Langnes~61890/varsel.xml"},
            {"Solbergfoss Kraftverk", "http://www.yr.no/sted/Norge/Østfold/Askim/Solbergfoss_Kraftverk/varsel.xml"},
            {"Vamma bru", "http://www.yr.no/sted/Norge/Østfold/Askim/Vamma_bru/varsel.xml"},
            {"Eidsberg", "http://www.yr.no/sted/Norge/Østfold/Eidsberg/Eidsberg/varsel.xml"},
            {"Eidsberg kirke", "http://www.yr.no/sted/Norge/Østfold/Eidsberg/Eidsberg_kirke/varsel.xml"},
            {"Hærland kirke", "http://www.yr.no/sted/Norge/Østfold/Eidsberg/Hærland_kirke/varsel.xml"},
            {"Mysen", "http://www.yr.no/sted/Norge/Østfold/Eidsberg/Mysen/varsel.xml"},
            {"Mysen kirke", "http://www.yr.no/sted/Norge/Østfold/Eidsberg/Mysen_kirke/varsel.xml"},
            {"Slitu", "http://www.yr.no/sted/Norge/Østfold/Eidsberg/Slitu/varsel.xml"},
            {"Trømborg kirke", "http://www.yr.no/sted/Norge/Østfold/Eidsberg/Trømborg_kirke/varsel.xml"},
            {"Berga", "http://www.yr.no/sted/Norge/Østfold/Skiptvet/Berga/varsel.xml"},
            {"Glenne", "http://www.yr.no/sted/Norge/Østfold/Skiptvet/Glenne~48103/varsel.xml"},
            {"Laum", "http://www.yr.no/sted/Norge/Østfold/Skiptvet/Laum/varsel.xml"},
            {"Meieribyen", "http://www.yr.no/sted/Norge/Østfold/Skiptvet/Meieribyen/varsel.xml"},
            {"Onstad", "http://www.yr.no/sted/Norge/Østfold/Skiptvet/Onstad/varsel.xml"},
            {"Skiptvet", "http://www.yr.no/sted/Norge/Østfold/Skiptvet/Skiptvet~507673/varsel.xml"},
            {"Skiptvet kirke", "http://www.yr.no/sted/Norge/Østfold/Skiptvet/Skiptvet_kirke/varsel.xml"},
            {"Vister", "http://www.yr.no/sted/Norge/Østfold/Skiptvet/Vister/varsel.xml"},
            {"Åmot", "http://www.yr.no/sted/Norge/Østfold/Skiptvet/Åmot/varsel.xml"},
            {"Degernes", "http://www.yr.no/sted/Norge/Østfold/Rakkestad/Degernes/varsel.xml"},
            {"Degernes kirke", "http://www.yr.no/sted/Norge/Østfold/Rakkestad/Degernes_kirke/varsel.xml"},
            {"Gautestad", "http://www.yr.no/sted/Norge/Østfold/Rakkestad/Gautestad/varsel.xml"},
            {"Kirkeng", "http://www.yr.no/sted/Norge/Østfold/Rakkestad/Kirkeng~2231362/varsel.xml"},
            {"Kirkeng skole", "http://www.yr.no/sted/Norge/Østfold/Rakkestad/Kirkeng_skole/varsel.xml"},
            {"Os kirke", "http://www.yr.no/sted/Norge/Østfold/Rakkestad/Os_kirke/varsel.xml"},
            {"Rakkestad", "http://www.yr.no/sted/Norge/Østfold/Rakkestad/Rakkestad/varsel.xml"},
            {"Rakkestad", "http://www.yr.no/sted/Norge/Østfold/Rakkestad/Rakkestad~48055/varsel.xml"},
            {"Rakkestad flyplass, Åstorp", "http://www.yr.no/sted/Norge/Østfold/Rakkestad/Rakkestad_flyplass,_Åstorp/varsel.xml"},
            {"Rakkestad kirke", "http://www.yr.no/sted/Norge/Østfold/Rakkestad/Rakkestad_kirke/varsel.xml"},
            {"Skantebygda", "http://www.yr.no/sted/Norge/Østfold/Rakkestad/Skantebygda/varsel.xml"},
            {"Skjekle", "http://www.yr.no/sted/Norge/Østfold/Rakkestad/Skjekle/varsel.xml"},
            {"Vaterland", "http://www.yr.no/sted/Norge/Østfold/Rakkestad/Vaterland/varsel.xml"},
            {"Ytterskogen", "http://www.yr.no/sted/Norge/Østfold/Rakkestad/Ytterskogen/varsel.xml"},
            {"Fuglevik", "http://www.yr.no/sted/Norge/Østfold/Råde/Fuglevik/varsel.xml"},
            {"Karlshus", "http://www.yr.no/sted/Norge/Østfold/Råde/Karlshus/varsel.xml"},
            {"Moss lufthavn Rygge", "http://www.yr.no/sted/Norge/Østfold/Råde/Moss_lufthavn_Rygge/varsel.xml"},
            {"Moss lufthavn Rygge", "http://www.yr.no/sted/Norge/Østfold/Råde/Moss_lufthavn_Rygge/varsel.xml"},
            {"Råde", "http://www.yr.no/sted/Norge/Østfold/Råde/Råde~47344/varsel.xml"},
            {"Råde kirke", "http://www.yr.no/sted/Norge/Østfold/Råde/Råde_kirke/varsel.xml"},
            {"Saltnes", "http://www.yr.no/sted/Norge/Østfold/Råde/Saltnes/varsel.xml"},
            {"Spetalen", "http://www.yr.no/sted/Norge/Østfold/Råde/Spetalen/varsel.xml"},
            {"Store Sletter", "http://www.yr.no/sted/Norge/Østfold/Råde/Store_Sletter/varsel.xml"},
            {"Tomb", "http://www.yr.no/sted/Norge/Østfold/Råde/Tomb/varsel.xml"},
            {"Tomb kirke", "http://www.yr.no/sted/Norge/Østfold/Råde/Tomb_kirke/varsel.xml"},
            {"Dilling", "http://www.yr.no/sted/Norge/Østfold/Rygge/Dilling~46640/varsel.xml"},
            {"Dilling", "http://www.yr.no/sted/Norge/Østfold/Rygge/Dilling~2723441/varsel.xml"},
            {"Ekholt kirke", "http://www.yr.no/sted/Norge/Østfold/Rygge/Ekholt_kirke/varsel.xml"},
            {"Fuglevik mellem", "http://www.yr.no/sted/Norge/Østfold/Rygge/Fuglevik_mellem/varsel.xml"},
            {"Fuglevik nordre", "http://www.yr.no/sted/Norge/Østfold/Rygge/Fuglevik_nordre/varsel.xml"},
            {"Fuglevik søndre", "http://www.yr.no/sted/Norge/Østfold/Rygge/Fuglevik_søndre/varsel.xml"},
            {"Garnbakken", "http://www.yr.no/sted/Norge/Østfold/Rygge/Garnbakken/varsel.xml"},
            {"Halmstad", "http://www.yr.no/sted/Norge/Østfold/Rygge/Halmstad~2274959/varsel.xml"},
            {"Larkollen", "http://www.yr.no/sted/Norge/Østfold/Rygge/Larkollen/varsel.xml"},
            {"Larkollen kirke", "http://www.yr.no/sted/Norge/Østfold/Rygge/Larkollen_kirke/varsel.xml"},
            {"Rygge", "http://www.yr.no/sted/Norge/Østfold/Rygge/Rygge/varsel.xml"},
            {"Rygge", "http://www.yr.no/sted/Norge/Østfold/Rygge/Rygge/varsel.xml"},
            {"Rygge", "http://www.yr.no/sted/Norge/Østfold/Rygge/Rygge/varsel.xml"},
            {"Rygge", "http://www.yr.no/sted/Norge/Østfold/Rygge/Rygge~2274955/varsel.xml"},
            {"Rygge kirke", "http://www.yr.no/sted/Norge/Østfold/Rygge/Rygge_kirke/varsel.xml"},
            {"Rådeskogen", "http://www.yr.no/sted/Norge/Østfold/Rygge/Rådeskogen/varsel.xml"},
            {"Fosseberget", "http://www.yr.no/sted/Norge/Østfold/Våler/Fosseberget~2718689/varsel.xml"},
            {"Kirkebygda", "http://www.yr.no/sted/Norge/Østfold/Våler/Kirkebygda/varsel.xml"},
            {"Kjærsund", "http://www.yr.no/sted/Norge/Østfold/Våler/Kjærsund~47190/varsel.xml"},
            {"Rød", "http://www.yr.no/sted/Norge/Østfold/Våler/Rød/varsel.xml"},
            {"Sperrebotn", "http://www.yr.no/sted/Norge/Østfold/Våler/Sperrebotn/varsel.xml"},
            {"Svinndal", "http://www.yr.no/sted/Norge/Østfold/Våler/Svinndal/varsel.xml"},
            {"Svinndal kirke", "http://www.yr.no/sted/Norge/Østfold/Våler/Svinndal_kirke/varsel.xml"},
            {"Teksnes", "http://www.yr.no/sted/Norge/Østfold/Våler/Teksnes/varsel.xml"},
            {"Våler kirke", "http://www.yr.no/sted/Norge/Østfold/Våler/Våler_kirke/varsel.xml"},
            {"Østre Veidal", "http://www.yr.no/sted/Norge/Østfold/Våler/Østre_Veidal/varsel.xml"},
            {"Elvestad", "http://www.yr.no/sted/Norge/Østfold/Hobøl/Elvestad/varsel.xml"},
            {"Hobøl kirke", "http://www.yr.no/sted/Norge/Østfold/Hobøl/Hobøl_kirke/varsel.xml"},
            {"Knappstad", "http://www.yr.no/sted/Norge/Østfold/Hobøl/Knappstad/varsel.xml"},
            {"Lippestad nordre", "http://www.yr.no/sted/Norge/Østfold/Hobøl/Lippestad_nordre/varsel.xml"},
            {"Ringvoll", "http://www.yr.no/sted/Norge/Østfold/Hobøl/Ringvoll/varsel.xml"},
            {"Tomter", "http://www.yr.no/sted/Norge/Østfold/Hobøl/Tomter/varsel.xml"},
            {"Tomter kirke", "http://www.yr.no/sted/Norge/Østfold/Hobøl/Tomter_kirke/varsel.xml"},
            {"Vestre Knapstad", "http://www.yr.no/sted/Norge/Østfold/Hobøl/Vestre_Knapstad/varsel.xml"},
            {"Bergli", "http://www.yr.no/sted/Norge/Akershus/Vestby/Bergli/varsel.xml"},
            {"Brevikmyra", "http://www.yr.no/sted/Norge/Akershus/Vestby/Brevikmyra/varsel.xml"},
            {"Fjell", "http://www.yr.no/sted/Norge/Akershus/Vestby/Fjell/varsel.xml"},
            {"Furulund", "http://www.yr.no/sted/Norge/Akershus/Vestby/Furulund/varsel.xml"},
            {"Garder", "http://www.yr.no/sted/Norge/Akershus/Vestby/Garder/varsel.xml"},
            {"Glenne", "http://www.yr.no/sted/Norge/Akershus/Vestby/Glenne/varsel.xml"},
            {"Holen", "http://www.yr.no/sted/Norge/Akershus/Vestby/Holen/varsel.xml"},
            {"Hvitsten", "http://www.yr.no/sted/Norge/Akershus/Vestby/Hvitsten/varsel.xml"},
            {"Hvitsten kirke", "http://www.yr.no/sted/Norge/Akershus/Vestby/Hvitsten_kirke/varsel.xml"},
            {"Høgda", "http://www.yr.no/sted/Norge/Akershus/Vestby/Høgda/varsel.xml"},
            {"Hølen", "http://www.yr.no/sted/Norge/Akershus/Vestby/Hølen/varsel.xml"},
            {"Kjenn", "http://www.yr.no/sted/Norge/Akershus/Vestby/Kjenn/varsel.xml"},
            {"Kjøvangen", "http://www.yr.no/sted/Norge/Akershus/Vestby/Kjøvangen/varsel.xml"},
            {"Krusebyen", "http://www.yr.no/sted/Norge/Akershus/Vestby/Krusebyen/varsel.xml"},
            {"Lundeåsen", "http://www.yr.no/sted/Norge/Akershus/Vestby/Lundeåsen/varsel.xml"},
            {"Okseryggen", "http://www.yr.no/sted/Norge/Akershus/Vestby/Okseryggen/varsel.xml"},
            {"Pepperstad skog", "http://www.yr.no/sted/Norge/Akershus/Vestby/Pepperstad_skog/varsel.xml"},
            {"Skoglundåsen", "http://www.yr.no/sted/Norge/Akershus/Vestby/Skoglundåsen/varsel.xml"},
            {"Smørbekk", "http://www.yr.no/sted/Norge/Akershus/Vestby/Smørbekk/varsel.xml"},
            {"Sollia", "http://www.yr.no/sted/Norge/Akershus/Vestby/Sollia/varsel.xml"},
            {"Son", "http://www.yr.no/sted/Norge/Akershus/Vestby/Son/varsel.xml"},
            {"Sorgenfri", "http://www.yr.no/sted/Norge/Akershus/Vestby/Sorgenfri/varsel.xml"},
            {"Stenløkka", "http://www.yr.no/sted/Norge/Akershus/Vestby/Stenløkka/varsel.xml"},
            {"Stjernåsen", "http://www.yr.no/sted/Norge/Akershus/Vestby/Stjernåsen/varsel.xml"},
            {"Store Brevik", "http://www.yr.no/sted/Norge/Akershus/Vestby/Store_Brevik/varsel.xml"},
            {"Strømbråten", "http://www.yr.no/sted/Norge/Akershus/Vestby/Strømbråten/varsel.xml"},
            {"Strømbråten kapell", "http://www.yr.no/sted/Norge/Akershus/Vestby/Strømbråten_kapell/varsel.xml"},
            {"Såner", "http://www.yr.no/sted/Norge/Akershus/Vestby/Såner/varsel.xml"},
            {"Utsikten", "http://www.yr.no/sted/Norge/Akershus/Vestby/Utsikten/varsel.xml"},
            {"Verpet", "http://www.yr.no/sted/Norge/Akershus/Vestby/Verpet/varsel.xml"},
            {"Vestby", "http://www.yr.no/sted/Norge/Akershus/Vestby/Vestby/varsel.xml"},
            {"Vestby", "http://www.yr.no/sted/Norge/Akershus/Vestby/Vestby~60953/varsel.xml"},
            {"Vestby", "http://www.yr.no/sted/Norge/Akershus/Vestby/Vestby~60947/varsel.xml"},
            {"Vollehagen", "http://www.yr.no/sted/Norge/Akershus/Vestby/Vollehagen/varsel.xml"},
            {"Århus", "http://www.yr.no/sted/Norge/Akershus/Vestby/Århus/varsel.xml"},
            {"Bru", "http://www.yr.no/sted/Norge/Akershus/Ski/Bru/varsel.xml"},
            {"Kråkstad", "http://www.yr.no/sted/Norge/Akershus/Ski/Kråkstad/varsel.xml"},
            {"Kråkstad", "http://www.yr.no/sted/Norge/Akershus/Ski/Kråkstad~60560/varsel.xml"},
            {"Langhus", "http://www.yr.no/sted/Norge/Akershus/Ski/Langhus/varsel.xml"},
            {"Langhus", "http://www.yr.no/sted/Norge/Akershus/Ski/Langhus~2233474/varsel.xml"},
            {"Siggerud", "http://www.yr.no/sted/Norge/Akershus/Ski/Siggerud/varsel.xml"},
            {"Siggerud", "http://www.yr.no/sted/Norge/Akershus/Ski/Siggerud~74401/varsel.xml"},
            {"Ski", "http://www.yr.no/sted/Norge/Akershus/Ski/Ski/varsel.xml"},
            {"Ski flyplass", "http://www.yr.no/sted/Norge/Akershus/Ski/Ski_flyplass/varsel.xml"},
            {"Ski middelalderkirke", "http://www.yr.no/sted/Norge/Akershus/Ski/Ski_middelalderkirke/varsel.xml"},
            {"Skotbu", "http://www.yr.no/sted/Norge/Akershus/Ski/Skotbu/varsel.xml"},
            {"Sterkerud", "http://www.yr.no/sted/Norge/Akershus/Ski/Sterkerud/varsel.xml"},
            {"Sørmarkskapellet", "http://www.yr.no/sted/Norge/Akershus/Ski/Sørmarkskapellet/varsel.xml"},
            {"Blåfjellet", "http://www.yr.no/sted/Norge/Akershus/Ås/Blåfjellet/varsel.xml"},
            {"Kjøya", "http://www.yr.no/sted/Norge/Akershus/Ås/Kjøya/varsel.xml"},
            {"Kroer", "http://www.yr.no/sted/Norge/Akershus/Ås/Kroer/varsel.xml"},
            {"Lier", "http://www.yr.no/sted/Norge/Akershus/Ås/Lier/varsel.xml"},
            {"Melby", "http://www.yr.no/sted/Norge/Akershus/Ås/Melby/varsel.xml"},
            {"Nesset", "http://www.yr.no/sted/Norge/Akershus/Ås/Nesset/varsel.xml"},
            {"Nordby", "http://www.yr.no/sted/Norge/Akershus/Ås/Nordby/varsel.xml"},
            {"Nordby", "http://www.yr.no/sted/Norge/Akershus/Ås/Nordby~60387/varsel.xml"},
            {"Solberg", "http://www.yr.no/sted/Norge/Akershus/Ås/Solberg/varsel.xml"},
            {"Solhaug", "http://www.yr.no/sted/Norge/Akershus/Ås/Solhaug/varsel.xml"},
            {"Tandbergløkka", "http://www.yr.no/sted/Norge/Akershus/Ås/Tandbergløkka/varsel.xml"},
            {"Vinterbro", "http://www.yr.no/sted/Norge/Akershus/Ås/Vinterbro/varsel.xml"},
            {"Vinterbro", "http://www.yr.no/sted/Norge/Akershus/Ås/Vinterbro~2247187/varsel.xml"},
            {"Vollholen", "http://www.yr.no/sted/Norge/Akershus/Ås/Vollholen/varsel.xml"},
            {"Ås", "http://www.yr.no/sted/Norge/Akershus/Ås/Ås/varsel.xml"},
            {"Ås", "http://www.yr.no/sted/Norge/Akershus/Ås/Ås~60637/varsel.xml"},
            {"Ås", "http://www.yr.no/sted/Norge/Akershus/Ås/Ås~60592/varsel.xml"},
            {"Brevik", "http://www.yr.no/sted/Norge/Akershus/Frogn/Brevik/varsel.xml"},
            {"Dammen", "http://www.yr.no/sted/Norge/Akershus/Frogn/Dammen/varsel.xml"},
            {"Digerud", "http://www.yr.no/sted/Norge/Akershus/Frogn/Digerud/varsel.xml"},
            {"Drøbak", "http://www.yr.no/sted/Norge/Akershus/Frogn/Drøbak/varsel.xml"},
            {"Drøbak kirke", "http://www.yr.no/sted/Norge/Akershus/Frogn/Drøbak_kirke/varsel.xml"},
            {"Dyrløkke", "http://www.yr.no/sted/Norge/Akershus/Frogn/Dyrløkke/varsel.xml"},
            {"Frogn", "http://www.yr.no/sted/Norge/Akershus/Frogn/Frogn~60453/varsel.xml"},
            {"Heer", "http://www.yr.no/sted/Norge/Akershus/Frogn/Heer/varsel.xml"},
            {"Heer", "http://www.yr.no/sted/Norge/Akershus/Frogn/Heer/varsel.xml"},
            {"Holmen", "http://www.yr.no/sted/Norge/Akershus/Frogn/Holmen/varsel.xml"},
            {"Kleiva", "http://www.yr.no/sted/Norge/Akershus/Frogn/Kleiva/varsel.xml"},
            {"Langebåtfeltet", "http://www.yr.no/sted/Norge/Akershus/Frogn/Langebåtfeltet/varsel.xml"},
            {"Marikova", "http://www.yr.no/sted/Norge/Akershus/Frogn/Marikova/varsel.xml"},
            {"Nordre Hallangen", "http://www.yr.no/sted/Norge/Akershus/Frogn/Nordre_Hallangen/varsel.xml"},
            {"Oscarsborg", "http://www.yr.no/sted/Norge/Akershus/Frogn/Oscarsborg/varsel.xml"},
            {"Rødsholtet", "http://www.yr.no/sted/Norge/Akershus/Frogn/Rødsholtet/varsel.xml"},
            {"Seiersten", "http://www.yr.no/sted/Norge/Akershus/Frogn/Seiersten/varsel.xml"},
            {"Skiphelle", "http://www.yr.no/sted/Norge/Akershus/Frogn/Skiphelle/varsel.xml"},
            {"Sogsti", "http://www.yr.no/sted/Norge/Akershus/Frogn/Sogsti/varsel.xml"},
            {"Solhøgda", "http://www.yr.no/sted/Norge/Akershus/Frogn/Solhøgda/varsel.xml"},
            {"Spervika", "http://www.yr.no/sted/Norge/Akershus/Frogn/Spervika/varsel.xml"},
            {"Tiurlia", "http://www.yr.no/sted/Norge/Akershus/Frogn/Tiurlia/varsel.xml"},
            {"Østskogen", "http://www.yr.no/sted/Norge/Akershus/Frogn/Østskogen/varsel.xml"},
            {"Alværn", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Alværn/varsel.xml"},
            {"Bekk", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Bekk/varsel.xml"},
            {"Berger", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Berger/varsel.xml"},
            {"Bjørnemyrdalen", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Bjørnemyrdalen/varsel.xml"},
            {"Bomansvik", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Bomansvik/varsel.xml"},
            {"Brubakken", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Brubakken/varsel.xml"},
            {"Fagerstrand", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Fagerstrand/varsel.xml"},
            {"Fjellstrand", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Fjellstrand/varsel.xml"},
            {"Fjordvangen", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Fjordvangen/varsel.xml"},
            {"Flaskebekk", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Flaskebekk/varsel.xml"},
            {"Flaskebekkbråten", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Flaskebekkbråten/varsel.xml"},
            {"Flauet", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Flauet/varsel.xml"},
            {"Gjøfjell", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Gjøfjell/varsel.xml"},
            {"Hellvik", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Hellvik/varsel.xml"},
            {"Kirkeåsen", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Kirkeåsen/varsel.xml"},
            {"Leina", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Leina/varsel.xml"},
            {"Lunner", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Lunner/varsel.xml"},
            {"Løkkeåsen", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Løkkeåsen/varsel.xml"},
            {"Nesodden", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Nesodden~73289/varsel.xml"},
            {"Nesoddtangen", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Nesoddtangen/varsel.xml"},
            {"Nordre Spro", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Nordre_Spro/varsel.xml"},
            {"Nordstrand", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Nordstrand/varsel.xml"},
            {"Oksval", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Oksval/varsel.xml"},
            {"Sjøstrand", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Sjøstrand/varsel.xml"},
            {"Skoklefall", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Skoklefall/varsel.xml"},
            {"Svestad", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Svestad/varsel.xml"},
            {"Søndre Ommen", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Søndre_Ommen/varsel.xml"},
            {"Søndre Spro", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Søndre_Spro/varsel.xml"},
            {"Toppen", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Toppen/varsel.xml"},
            {"Torget", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Torget/varsel.xml"},
            {"Ursvik", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Ursvik/varsel.xml"},
            {"Varden", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Varden/varsel.xml"},
            {"Vestli", "http://www.yr.no/sted/Norge/Akershus/Nesodden/Vestli/varsel.xml"},
            {"Båtsleppa", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Båtsleppa/varsel.xml"},
            {"Greverud", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Greverud~511628/varsel.xml"},
            {"Greverud", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Greverud/varsel.xml"},
            {"Hellerasten", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Hellerasten/varsel.xml"},
            {"Ingieråsen", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Ingieråsen/varsel.xml"},
            {"Kolbotn", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Kolbotn/varsel.xml"},
            {"Kolbotn", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Kolbotn~74344/varsel.xml"},
            {"Myrvoll", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Myrvoll~511909/varsel.xml"},
            {"Nordre Ødegården", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Nordre_Ødegården/varsel.xml"},
            {"Oppegård", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Oppegård/varsel.xml"},
            {"Oppegård", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Oppegård~511629/varsel.xml"},
            {"Oppegård", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Oppegård~74468/varsel.xml"},
            {"Rasten", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Rasten/varsel.xml"},
            {"Ryberg", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Ryberg/varsel.xml"},
            {"Sofiemyr", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Sofiemyr~74394/varsel.xml"},
            {"Sofiemyr", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Sofiemyr/varsel.xml"},
            {"Svartskog", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Svartskog/varsel.xml"},
            {"Sætreskogen", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Sætreskogen/varsel.xml"},
            {"Søndre Oppegård", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Søndre_Oppegård/varsel.xml"},
            {"Tårnåsen", "http://www.yr.no/sted/Norge/Akershus/Oppegård/Tårnåsen~74308/varsel.xml"},
            {"Bekkestua", "http://www.yr.no/sted/Norge/Akershus/Bærum/Bekkestua/varsel.xml"},
            {"Brunkollen turisthytte", "http://www.yr.no/sted/Norge/Akershus/Bærum/Brunkollen_turisthytte/varsel.xml"},
            {"Bryn", "http://www.yr.no/sted/Norge/Akershus/Bærum/Bryn/varsel.xml"}};
}
